import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import Navigation from '@/app/components/Navigation';

import { useState } from 'react';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation isAuthenticated={isAuthenticated} />
        <main>
          <div className="px-4 sm:px-6 lg:px-8">{children}</div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
